### ISSUE TITLE
fedora 22 linux: crash on TASServer::OnDisconnected()

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#533]
CRASH LOGS: http://pastebin.com/6Uagr2ye

Steps to reproduce:
1) start lobby and resize any column on the "battlelist" tab
2) close the lobby

expected result: column width is saved, lobby closed
actual result: lobby crashed, column width is not saved

springlobby is latest from git: 
0.225-133-gfc9c0fe

system info:
SpringLobby 0.225-133-gfc9c0fe (unix x64)
SpringLobby config file: /home/revenant/.springlobby/springlobby.conf ( writable)
LobbyWriteDir (/home/revenant/.springlobby/)
	WX: yes POSIX: yes TRY: yes
CachePath (/home/revenant/.springlobby/cache/)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (/home/revenant/springlobby/src/)
	WX: yes POSIX: yes TRY: yes
DownloadDir (/home/revenant/.spring/)
	WX: yes POSIX: yes TRY: yes
Current SpringData: (/home/revenant/.config/spring/)
	WX: yes POSIX: yes TRY: yes
Current unitsync: /home/revenant/.spring/engine/100.0/libunitsync.so
Current spring executable: /home/revenant/.spring/engine/100.0/spring
Current uikeys.txt: /home/revenant/.config/spring/uikeys.txt
Portable mode: no
Compiled with wxWidgets 3.0.2.0

**Comment by Usaga** [comment]
This bag is being investigated, but hard to reproduce...

**Comment by Usaga** [comment]
Probably related to #532

**Comment by Usaga** [comment]
Test it please, now it should work properly. I hope.

**Comment by jamerlan** [comment]
still crashing http://pastebin.com/bvMez5Jy

**Comment by Usaga** [comment]
This log makes it clear where the problem is... I will fix it today.

**Comment by Usaga** [comment]
This looks like particular bug in your distro - wxGtk tries to update BattleDataView control after it has been cleared. Maybe some workaround is needed.

**Comment by abma** [comment]
maybe flip these lines in inline void BaseDataViewModel<DataType>::Clear():

    m_ModelData.clear();
    Cleared();

?

**Comment by Usaga** [comment]
I thought about it. It may or may not help. I need to get my PC at home with virtual linux box and experiment with it))) You may flip this line to see what happens.

**Comment by jamerlan** [comment]
I tried to swap these lines in src/gui/basedataviewmodel.h
not helped. It still crashes on exit

**Comment by Usaga** [comment]
I trying to find tje solution

**Comment by Usaga** [comment]
Abma, do you have same bug?

**Comment by jamerlan** [comment]
I can give access to my PC via team viewer to both of you. Just send me PM in lobby. I will show where are the sources and you will be able to test / develop / investigate

**Comment by Usaga** [comment]
This is not needed, I can reproduce it on virtual pc with fedora.

**Comment by Usaga** [comment]
I had not enough time after work to investigate this problem properly. All I can say, that this bug does not shows itself on Ubuntu 15.04... Same for scrolling with mouse wheel - it works on Ubuntu but not on Fedora. Maybe this is some regression bugs in Fedora itself? Any way this must be solved some how.

**Comment by abma** [comment]
which version of wxWidgets is used? possible this is just a wxwidgets bug...

afaik mouse wheel scrolling is fixed in newer versions of wxwidgets.

**Comment by abma** [comment]
mouse wheel scrolling could be this report: http://trac.wxwidgets.org/ticket/2623

**Comment by jamerlan** [comment]
just re-tested latest version. Still crashes:
http://pastebin.com/Lu9Hgdsz

**Comment by abma** [comment]
tried on fedora 22, too, but i couldn't find a way to fix it :-| very strange error.

on fedora i get a lot of compile warnings about deprecated stuff used, not sure whats wrong there.

**Comment by jamerlan** [comment]
interesting thing is: previous release was working good. So it must be smth in this "release"

**Comment by abma** [comment]
not really interesting, all lists where rewritten from scratch:
https://github.com/springlobby/springlobby/blob/master/ChangeLog#L4

**Comment by jamerlan** [comment]
I wanted to motivate you with: you did smth wrong :-D

**Comment by abma** [comment]
thats not motivating, just frustrating

**Comment by abma** [comment]
Clear calls  wxDataViewModel::Cleared():
https://github.com/wxWidgets/wxWidgets/blob/master/src/gtk/dataview.cpp#L1780

which calls gtk_tree_model_row_deleted:
https://developer.gnome.org/gtk3/stable/GtkTreeModel.html#gtk-tree-model-row-deleted
"Nodes that are deleted are not unreffed, this means that any outstanding references on the deleted node should not be released."

not sure how this is meant...

**Comment by abma** [comment]
https://github.com/wxWidgets/wxWidgets/blob/master/src/gtk/dataview.cpp#L1782
 gtk_tree_path_free is called after gtk_tree_model_row_deleted, so flipping the lines

    m_ModelData.clear();
    Cleared();

looks more correct to me.

**Comment by abma** [comment]
oO
now it crashes for me on ubuntu?!
http://paste.springfiles.com/view/de692bb1

**Comment by Usaga** [comment]
For me it crashes in MapCtrl::UpdateMinimap()

**Comment by abma** [comment]
stacktrace please!

**Comment by Usaga** [comment]
![image](https://cloud.githubusercontent.com/assets/10685845/9202765/452a40ae-4075-11e5-9eb0-22ac2b25df32.png)

**Comment by Usaga** [comment]
Can't paste text - clipboard does not work from VM to Windows...

**Comment by Usaga** [comment]
Call #13 - wxdataview_selection_changed_callback called after wxDataViewCtrl been cleard. That is odd but should not lead to problem - BattleListTab::OnSelect will receive nullptr from BaseDataView (it check if model is empty) but it does not O_o

**Comment by abma** [comment]
wrong order of de-init?

**Comment by Usaga** [comment]
I am not sure

**Comment by Usaga** [comment]
I figured out the reason of the crash: if item in dataview is selected while clearing, wx tries to select another item which is invalid because SL is disconnected. If no item selected SL shuts down properly. Need to clear selection before clearing somehow...

**Comment by Usaga** [comment]
Nope, still crashing...

**Comment by abma** [comment]
stacktrace please...

**Comment by abma** [comment]
also, does it crash in OnDisconnected or not? if not, please create a new issue
