### ISSUE TITLE
*** Caught unhandled exception; terminating when updating

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#536]
not sure when this was introduced, needs to be fixed before release.

**Comment by abma** [comment]
@Usaga can you please fix that?

why are exceptions used in contentmanager? i don't see the benefit... imo it makes code unreadable / requires try/catch everywhere :-|

**Comment by abma** [comment]
error is that Ui::CheckForUpdates() calls contentmanager which throws exceptions which aren't handled.

**Comment by Usaga** [comment]
Ok, I will fix that.

**Comment by Usaga** [comment]
The benefit was in method's ability to say what was wrong - erro detailed error msm in ecpetion instance.

**Comment by Usaga** [comment]
This exception rising only when updating or even when downloading maps/mods?

**Comment by abma** [comment]
both, i get unhandled exceptions when updating and downloading maps/games.

**Comment by Usaga** [comment]
Mythsticks

**Comment by abma** [comment]
> The benefit was in method's ability to say what was wrong - erro detailed error msm in ecpetion instance.

wxLogError() could do the same. this:

try {
	ContentManager::Instance()->DownloadContent(req);
} catch (Exception& e) {
	wxLogError(e.Reason());
	return;
}

does basicly the same as when replacing the exceptions with wxLogError and removing try/catch. i know, some flexibility is lost then, but without exceptions code (imo) is more readable and its not so easy to introduce bugs by forgetting to catch exceptions. also finding the source of the unhandled exception can be difficult it seems.

just my two cents and fat note: i'm more a c programmer than high-level coder.

**Comment by Usaga** [comment]
I agree that wxLogError is much easy to understand/read but only if method return true/false. Basic idea of using exception mechanics here is not only to know method has failed but also understand why it had happened. I mean some detailed information about error. I though user must be informed why he can't get content. So I see two way to do that: use some "C" method like ContentManager->GetErrorString() or to use exceptions...

I used exceptions here only to be able infom user with details of error. I agree it is not so convenient to use exceptions everywhere...

**Comment by Usaga** [comment]
I think I fixed this. Test it please. And sorry for the dumb code.

**Comment by abma** [comment]
i still get an "unhandled exception" when doing a stock install:

(delete or rename)
delete %appdata%\springlobby
delete my games\spring

start springlobby, login to lobby server, click yes when asked for spring 100.0 download, join battle, click yes to allow download -> unhandled exception

**Comment by abma** [comment]
i'm blind, i don't see a message in the log file :-|

**Comment by Usaga** [comment]
Fixed with 7644163f0b264b8a2626b28908b04353d6df6ae7
