### ISSUE TITLE
crash on open

### ISSUE THREAD

**Issue by CognitivelyChallenged** [springlobby/springlobby#845]
after downloading all the engines most of the games (some test and dev won't download) and most of the maps springlobby would crash without opening.
[springlobby.log](https://github.com/springlobby/springlobby/files/1864666/springlobby.log)

using ubuntu 17.10, 15.6 GiB,  i7-3630QM on a hp notebook

**Comment by abma** [comment]
spring 101 makes it crash: try to delete:

/home/guest/.spring/engine/101.0/

should fix the crash. only one autohost seems to use this old version: i think / hope this shouldn't be an issue as its very likely not needed.

**Comment by CognitivelyChallenged** [comment]
still crashes before it opens
[springlobby.log](https://github.com/springlobby/springlobby/files/1865666/springlobby.log)

but after i removed them all it worked.

**Comment by abma** [comment]
very likely a duplicate of #855
both crashes here are inside libunitsync.so
